-- MySQL Script generated by MySQL Workbench
-- Thu Dec 15 16:24:38 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`se_cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`se_cargo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`se_cargo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`se_ccosto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`se_ccosto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`se_ccosto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`se_grado_inst`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`se_grado_inst` ;

CREATE TABLE IF NOT EXISTS `mydb`.`se_grado_inst` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descriocion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`se_empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`se_empleado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`se_empleado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `id_cargo` INT NULL,
  `id_ccosto` INT NULL,
  `fecha_ingreso` DATE NULL,
  `se_grado_inst_id` INT NOT NULL,
  PRIMARY KEY (`id`, `se_grado_inst_id`),
  INDEX `fk_se_empleado_se_cargo_idx` (`id_cargo` ASC) VISIBLE,
  INDEX `fk_se_empleado_se_ccosto_idx` (`id_ccosto` ASC) VISIBLE,
  INDEX `fk_se_empleado_se_grado_inst1_idx` (`se_grado_inst_id` ASC) VISIBLE,
  CONSTRAINT `fk_se_empleado_se_cargo`
    FOREIGN KEY (`id_cargo`)
    REFERENCES `mydb`.`se_cargo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_se_empleado_se_ccosto`
    FOREIGN KEY (`id_ccosto`)
    REFERENCES `mydb`.`se_ccosto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_se_empleado_se_grado_inst1`
    FOREIGN KEY (`se_grado_inst_id`)
    REFERENCES `mydb`.`se_grado_inst` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`se_factores_eval`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`se_factores_eval` ;

CREATE TABLE IF NOT EXISTS `mydb`.`se_factores_eval` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(250) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`se_item_factor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`se_item_factor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`se_item_factor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(2500) NULL,
  `peso` INT NULL,
  `id_factor` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sc_item_factor_sc_factores_eval1_idx` (`id_factor` ASC) VISIBLE,
  CONSTRAINT `fk_sc_item_factor_sc_factores_eval1`
    FOREIGN KEY (`id_factor`)
    REFERENCES `mydb`.`se_factores_eval` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`se_evaluacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`se_evaluacion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`se_evaluacion` (
  `fecha` VARCHAR(45) NULL,
  `puntaje` INT NULL,
  `se_empleado_id` INT NOT NULL,
  PRIMARY KEY (`se_empleado_id`),
  CONSTRAINT `fk_sc_evaluacion_se_empleado1`
    FOREIGN KEY (`se_empleado_id`)
    REFERENCES `mydb`.`se_empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`table1` ;

CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`se_eval_item_factor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`se_eval_item_factor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`se_eval_item_factor` (
  `valor` INT NOT NULL,
  `id_eval_emp` INT NOT NULL,
  `id_item_factor` INT NOT NULL,
  PRIMARY KEY (`valor`),
  INDEX `fk_se_eval_item_factor_sc_evaluacion1_idx` (`id_eval_emp` ASC) VISIBLE,
  INDEX `fk_se_eval_item_factor_sc_item_factor1_idx` (`id_item_factor` ASC) VISIBLE,
  CONSTRAINT `fk_se_eval_item_factor_sc_evaluacion1`
    FOREIGN KEY (`id_eval_emp`)
    REFERENCES `mydb`.`se_evaluacion` (`se_empleado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_se_eval_item_factor_sc_item_factor1`
    FOREIGN KEY (`id_item_factor`)
    REFERENCES `mydb`.`se_item_factor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
